### ISSUE TITLE
How to deploy both Container and Microfrontend for production?

### ISSUE THREAD

**Issue by Amishmaqbool** [JenniferFuBook/micro-frontend#1]
Hey I clone the microfronend and container app and now i am thinking of deploying it and as it is integrated on the run time how can i deploy both the app into production?

**Comment by JenniferFuBook** [comment]
Hi Amish, 

For the production mode, you can do it in three steps:
1. Publish the micro frontend app to be a NPM package. 
2. Install the package into the container app.
3. The container app  loads the package from the local node module.

Thanks,

Jennifer

**Comment by Amishmaqbool** [comment]
hey one more thing I am adding two microfrontends but one render and one does not.how can I add more than one micro frontend

**Comment by Amishmaqbool** [comment]
Thanks GOT it works great 👍🏻
